IonCard
iurynogueira/ion pull request #103
Opened 2022-08-23 14:17 UTC by MarcosOliveir4

2022-08-23 14:31 UTC, edsonsnunes commented on projects/ion/src/lib/card/card.component.scss
> +    border-bottom: 1px solid #ced2db;
Não seria $neutral-4?

2022-08-23 14:31 UTC, edsonsnunes commented on projects/ion/src/lib/card/card.component.scss
> +      color: #505566;
$neutral-7 ?

2022-08-23 14:32 UTC, edsonsnunes commented on projects/ion/src/lib/card/card.component.scss
> +    border-top: 1px solid #ced2db;
Aqui também

2022-08-23 17:28 UTC, iurynogueira requested changes
![gandalf](https://user-images.githubusercontent.com/6165180/186225238-db07f576-5645-424b-b12f-8849b82b559b.gif)

2022-08-23 17:28 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.spec.ts
> +      : { buttons: { primary: { label: 'iea' } } },
```suggestion
      : { buttons: { primary: { label: 'Confirmar' } } },
```

2022-08-23 17:28 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.spec.ts
> +    const fixture = TestBed.createComponent(CardTestComponent);
```suggestion
    const fixture = TestBed.createComponent(CardTestComponent);
```

create sut and return this fixture.

2022-08-23 17:28 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.spec.ts
> +  });
```suggestion
    TestBed.configureTestingModule({
      imports: [TestModule],
    }).compileComponents();
  });
```

add sut and fixture.detectChanges(); here.

2022-08-23 17:28 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.spec.ts
> +    fixture.destroy();
this destroy I suggest add in afterEach

2022-08-23 17:28 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.spec.ts
> +    expect(header.textContent).toBe('opa');
```suggestion
    expect(header.textContent).toBe(cardConfig.title);
```

2022-08-23 17:28 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.spec.ts
> +    header: { title: 'opa' },
create a card config object and put here

2022-08-23 17:28 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.spec.ts
> +    expect(header.textContent).toBe('Opa, eu fui clicado evento: primary');
We can test this case with spyOn?

2022-08-23 17:28 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.spec.ts
> +    expect(screen.getByTestId('footerTest')).toBeTruthy();
```suggestion
    expect(screen.getByTestId('footerTest')).toBeTruthy();
```
I believe that toBeInTheDocument make more sense.

2022-08-23 17:28 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.ts
> +  [keys in ButtonType]?: Pick<ButtonBase, 'label' | 'circular' | 'icon'>;
I like that

2022-08-23 17:28 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.ts
> +  bodyFooter?: ComponentType<SafeAny>;
```suggestion
  body?: ComponentType<SafeAny>;
```

2022-08-23 17:28 UTC, iurynogueira commented on stories/Card.stories.mdx
> +- `body`. Aqui é onde vai receber o componente que será renderizado no body do card.
```suggestion
- `body`. Receberá o componente para renderizar no body do card.
```

2022-08-24 15:04 UTC, mizek1 commented on projects/ion/src/lib/card/card.component.spec.ts
> +    TestBed.configureTestingModule({
Could you guys explain to me why TestBed is being used here instead of render? @iurynogueira @MarcosOliveir4

2022-08-24 15:05 UTC, mizek1 commented on projects/ion/src/lib/card/card.component.ts
> +  [keys in ButtonType]?: Pick<ButtonBase, 'label' | 'circular' | 'icon'>;
this is very cool 😎

2022-08-24 15:44 UTC, Deeved commented on projects/ion/src/lib/card/card.component.html
> +          (click)="cardEvent(button.nameAction)"
Poderia usar o próprio evento do botão

2022-08-24 15:47 UTC, Deeved commented on projects/ion/src/lib/card/card.component.ts
> +  [keys in ButtonType]?: Pick<ButtonBase, 'label' | 'circular' | 'icon'>;
I liked too.

2022-08-24 18:21 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.html
> +          (click)="cardEvent(button.nameAction)"
really

2022-08-25 19:19 UTC, MarcosOliveir4 commented on projects/ion/src/lib/card/card.component.html
> +          (click)="cardEvent(button.nameAction)"
nesse caso não posso, por que o evento do botão só diz que foi clicado eu preciso especificar qual é

2022-08-30 16:57 UTC, iurynogueira approved these changes

2022-08-31 11:47 UTC, lucasrasec approved these changes

2022-08-31 11:56 UTC, Deeved commented on projects/ion/src/lib/card/card.component.html
> +      <div class="card-ion-footer-containerButtons">
```suggestion
      <div class="card-ion-footer-container-buttons">
```

2022-08-31 12:04 UTC, Deeved commented on projects/ion/src/lib/card/card.component.scss
> +    padding: 16px 20px;
```suggestion
    padding: spacing(2) spacing(2.5);
```

2022-08-31 12:05 UTC, Deeved commented on projects/ion/src/lib/card/card.component.scss
> +    padding: spacing(2) 12px;
```suggestion
    padding: spacing(2) spacing(1.5);
```

2022-08-31 17:01 UTC, iurynogueira commented
Check min-height and padding title when has icon actions. Add a case in stories with body.

2022-08-31 17:02 UTC, iurynogueira requested changes
Check comments

2022-08-31 17:08 UTC, Deeved approved these changes

2022-09-01 13:45 UTC, iurynogueira approved these changes
Add stories in folder meta.

2022-09-01 18:05 UTC, merged