Add icon in card header
iurynogueira/ion pull request #135
Opened 2022-09-19 12:41 UTC by jairochaves2

2022-09-20 11:20 UTC, mizek1 approved these changes

2022-09-20 17:31 UTC, iurynogueira requested changes

2022-09-20 17:31 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.html
> +        data-testid="iconTitle"
```suggestion
        data-testid="icon-title"
```

2022-09-20 17:31 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.spec.ts
> +    expect(screen.getByTestId('iconTitle')).toBeInTheDocument();
```suggestion
    expect(screen.getByTestId('icon-title')).toBeInTheDocument();
```

2022-09-20 17:31 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.spec.ts
> +    expect(screen.queryByTestId('iconTitle')).toBeNull();
```suggestion
    expect(screen.queryByTestId('icon-title')).toBeNull();
```

2022-09-22 17:25 UTC, iurynogueira approved these changes

2022-09-22 17:41 UTC, MarcosOliveir4 approved these changes

2022-09-22 17:42 UTC, merged