:sparkles: Add CI/CD
iurynogueira/ion pull request #15
Opened 2022-07-11 17:13 UTC by MarcosOliveir4

2022-07-11 17:29 UTC, iurynogueira commented
Change node version to v12.22.1

2022-07-12 17:39 UTC, mizek1 approved these changes
Looks good.

2022-07-12 20:30 UTC, iurynogueira requested changes

2022-07-12 20:30 UTC, iurynogueira commented on .gitignore
> +# yarn.lock
```suggestion
yarn.lock
```

2022-07-12 20:30 UTC, iurynogueira commented on .gitignore
>  package-lock.json
Remove file

2022-07-14 12:40 UTC, iurynogueira approved these changes

2022-07-14 12:41 UTC, merged