Input component
iurynogueira/ion pull request #152
Opened 2022-09-26 13:58 UTC by edsonsnunes

2022-10-04 13:13 UTC, iurynogueira requested changes

2022-10-04 13:13 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.html
> +    style="padding-right: 8px"
```suggestion
    style="padding-right: 8px"
```
Add class to this, because this was repeat.

2022-10-04 13:13 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.spec.ts
> +    expect(screen.getByTestId('inputElement')).toHaveValue('input');
```suggestion
const inputValue = 'text to input'
    fireEvent.change(screen.getByTestId('inputElement'), {
      target: { value: inputValue },
    });
    expect(screen.getByTestId('inputElement')).toHaveValue(inputValue);
```

2022-10-04 13:13 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.spec.ts
> +  it('should render input icon left', async () => {
Add a new case to check if the icon its correct.

2022-10-04 13:13 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.spec.ts
> +    await sut({ iconDirection: 'left' });
```suggestion
    await sut({ iconDirection: 'left', icon: 'pencil' });
```

2022-10-06 12:17 UTC, Deeved commented on projects/ion/src/lib/input/input.component.html
> +  [class.valid]="valid"
não existe as propriedades `ìnvalid` e `valid` no input.component.ts

falta importar e exportar o componente no  ion.module.ts

2022-10-06 12:34 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.html
> +  [class.valid]="valid"
Nós vamos deixar o invalid e o valid ai para que fique "no jeito" para quando a gente fazer o form ele já ter os atributos.

2022-10-13 13:53 UTC, lucasrasec commented on projects/ion/src/lib/input/input.component.scss
> +  padding: 6px 12px;
You can use the "spacing" function to set the padding:

`padding: spacing(0.75) spacing(1.5);`

2022-10-13 14:12 UTC, lucasrasec commented on projects/ion/src/lib/input/input.component.scss
> +    padding-left: 20px;
`padding-left: spacing(2.5)`

2022-10-13 14:21 UTC, lucasrasec commented on projects/ion/src/lib/input/input.component.spec.ts
> +describe(InputComponent, () => {
Add quotes in the title of describe

`describe('InputComponent', ...`

2022-10-19 13:28 UTC, AlyssonMascarenhas requested changes

2022-10-19 13:28 UTC, AlyssonMascarenhas commented on stories/Input.stories.ts
> +import { IconDirection } from './../projects/ion/src/lib/input/input.component';
Aviso do test-prettier-lint

2022-10-19 13:28 UTC, AlyssonMascarenhas commented on projects/ion/src/lib/input/input.component.scss
> +    background: #fcfcfd;
```suggestion
    background: $neutral-1;
```

2022-10-20 14:23 UTC, iurynogueira requested changes
Check this points please

2022-10-20 14:23 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.scss
> +  border-radius: 8px;
spacing

2022-10-24 13:29 UTC, iurynogueira requested changes

2022-10-24 13:29 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.scss
> +    outline: 2px solid $primary-2;
create mixin for this

2022-10-24 13:29 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.spec.ts
> +  });
```suggestion
  it('should render input icon right', async () => {
    const icon = 'pencil';
    await sut({ iconDirection: 'right', iconInput: icon });
    expect(document.getElementById('ion-icon-' + icon)).toBeTruthy();
  });
```

2022-10-24 13:29 UTC, iurynogueira commented on stories/Input.stories.ts
> +  label: '',
Remove labels

2022-10-24 16:50 UTC, iurynogueira requested changes

2022-10-24 16:50 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.scss
> +    @include add-colors($negative-6, 2px, solid, $negative-1);
```suggestion
    @include add-colors($negative-6, 2px solid $negative-1);
```

this is possible?

2022-10-25 17:12 UTC, iurynogueira approved these changes

2022-10-26 12:01 UTC, AlyssonMascarenhas approved these changes
Great!

2022-10-26 17:25 UTC, merged