154 add dropdown in button
iurynogueira/ion pull request #160
Opened 2022-09-27 16:35 UTC by imrochamatheus

2022-09-29 19:46 UTC, iurynogueira commented
Add output in button to get option selected in dropdown

2022-10-04 13:31 UTC, iurynogueira commented
fix pipeline

2022-10-10 12:50 UTC, mizek1 commented
Check pipeline errors.
Apparently, in every component that button is declared/imported you'll need to declare badge and dropdown too.

2022-10-10 13:04 UTC, mizek1 requested changes
Good job!
Update your branch with main because there are new changes to dropdown and it may affect this features.

2022-10-10 13:04 UTC, mizek1 commented on projects/ion/src/lib/button/button.component.ts
> +  @Output() selected = new EventEmitter();
```suggestion
  @Output() selected = new EventEmitter<DropdownItem[]>();
```

2022-10-13 17:41 UTC, imrochamatheus commented on projects/ion/src/lib/button/button.component.spec.ts
> +describe('ButtonComponent with badge', () => {
show, added!

2022-10-24 12:40 UTC, iurynogueira approved these changes

2022-10-26 19:31 UTC, Deeved approved these changes

2022-10-27 13:01 UTC, merged