fix: autoclose in dropdown when select an option
iurynogueira/ion pull request #170
Opened 2022-10-04 14:26 UTC by PedroMiguel7

autoclose in dropdown when select an option

2022-10-04 14:50 UTC, iurynogueira requested changes

2022-10-04 14:50 UTC, iurynogueira commented on projects/ion/src/lib/chip/chip.component.spec.ts
> +      expect(element).toHaveClass('chip-selected');
You can remove this, not is necessary check class to this case.

```suggestion
```

2022-10-04 14:50 UTC, iurynogueira commented on projects/ion/src/lib/chip/chip.component.spec.ts
> +      expect(element).toHaveClass('chip');
You can add too a expect to check if any options not is in the document.
`expect(screen.queryAllByText(option)).toHaveLength(0)`

2022-10-10 12:14 UTC, mizek1 approved these changes

2022-10-10 12:34 UTC, iurynogueira approved these changes

2022-10-10 12:35 UTC, merged