fix: [ion-177] selection adjustment
iurynogueira/ion pull request #180
Opened 2022-10-05 19:36 UTC by MarcosOliveir4

2022-10-06 12:23 UTC, iurynogueira requested changes

2022-10-06 12:23 UTC, iurynogueira commented on projects/ion/src/lib/tab-group/tab-group.component.ts
> +  ChangeDetectorRef,
is defined but never used.

2022-10-06 12:23 UTC, iurynogueira commented on projects/ion/src/lib/tab/tab.component.ts
> +    }
I believe that you can do this.selected = true.
```suggestion
      this.selected = true;
```

2022-10-06 12:23 UTC, iurynogueira commented on projects/ion/src/lib/tab-group/tab-group.component.ts
> +      tabSelected.selected = true;
```suggestion
      tabSelected.select();
```

Call method, this way if there is a change in logic the behavior will be replicated here.

2022-10-06 12:24 UTC, AlyssonMascarenhas requested changes
Github Actions / test-prettier-lint:
'ChangeDetectorRef' is defined but never used.

2022-10-06 12:33 UTC, Deeved approved these changes

2022-10-10 12:22 UTC, allanplobo approved these changes

2022-10-10 12:46 UTC, iurynogueira approved these changes
nice work marquinhos!

![festa](https://user-images.githubusercontent.com/6165180/194869622-43f2d772-3c90-4f45-9a3e-66909778aa5b.gif)

2022-10-11 11:51 UTC, mizek1 approved these changes

2022-10-11 13:24 UTC, AlyssonMascarenhas approved these changes

2022-10-11 13:32 UTC, merged