162 create modal service
iurynogueira/ion pull request #223
Opened 2022-10-11 14:49 UTC by allanplobo

Cria o serviço e componente de modal para utilização no Ion

2022-10-14 12:53 UTC, iurynogueira requested changes
Nice work @allanplobo, we are happy with this contribution, it's very important to all projects.

2022-10-14 12:53 UTC, iurynogueira commented on projects/ion/src/lib/modal/component/modal.component.spec.ts
> +    });
```suggestion
    const escapeKeyCode = 27;
    fireEvent.keyDown(screen.getByTestId('modalOverlay'), {
      key: 'Escape',
      code: 'Escape',
      keyCode: escapeKeyCode,
      charCode: escapeKeyCode,
    });
```

2022-10-14 12:53 UTC, iurynogueira commented on projects/ion/src/lib/modal/component/modal.component.spec.ts
> +    expect(component.closeModal).not.toHaveBeenCalled();
This can be other test case, because not reflect your **it**.

2022-10-14 12:53 UTC, iurynogueira commented on projects/ion/src/lib/modal/component/modal.component.spec.ts
> +  });
https://github.com/Brisanet/typescript/blob/main/docs/Style%20Guide.md#whitespace---no-multiple-empty-lines

2022-10-14 12:53 UTC, iurynogueira commented on projects/ion/src/lib/modal/component/modal.component.spec.ts
> +  });
```suggestion
  it('should hide footer when its true on config', () => {
    const modalFooter = footer();
    component.config.footer.hide = true;
    fixture.detectChanges();
    expect(modalFooter).not.toBeInTheDocument();
  });
```

2022-10-14 12:53 UTC, iurynogueira commented on projects/ion/src/lib/modal/component/modal.component.spec.ts
> +    expect(component.ionOnClose.emit).toHaveBeenCalledWith({ state: 'Ceará' });
Great! 👏

2022-10-14 12:53 UTC, iurynogueira commented on projects/ion/src/lib/modal/ion-modal.service.spec.ts
> +  });
```suggestion
  it('should set title according to config in open function', () => {
    const title = 'modal title'
    modalService.open(
      fixture.componentInstance.container,
      SelectMockComponent,
      { title: title }
    );

    fixture.detectChanges();

    expect(screen.getByTestId('modalTitle').innerHTML).toBe(title);
  });
```

2022-10-14 12:53 UTC, iurynogueira commented on projects/ion/src/lib/modal/mock/open-modal.mock.component.ts
> +        console.log('value from modal service', response);
```suggestion
```

2022-10-14 12:53 UTC, iurynogueira commented on projects/ion/src/lib/modal/component/modal.component.ts
> +          label: 'Confirm',
```suggestion
          label: 'Confirmar',
```

2022-10-14 12:53 UTC, iurynogueira commented on projects/ion/src/lib/modal/component/modal.component.ts
> +          label: 'Cancel',
```suggestion
          label: 'Cancelar',
```

2022-10-18 00:37 UTC, allanplobo commented
> Nice work @allanplobo, we are happy with this contribution, it's very important to all projects.

Thanks, it's a pleasure to contribute to the project. And, of course, more will come! =D

2022-10-19 12:13 UTC, iurynogueira approved these changes
![festa](https://user-images.githubusercontent.com/6165180/196687252-04891f34-1324-48fb-99ad-c21213c84882.gif)

2022-10-21 11:42 UTC, Deeved approved these changes

2022-10-21 12:01 UTC, MarcosOliveir4 approved these changes

2022-10-21 18:47 UTC, merged