241 add new variant to alert component
iurynogueira/ion pull request #243
Opened 2022-10-25 11:41 UTC by VinicciusSantos

2022-10-25 13:53 UTC, iurynogueira requested changes

2022-10-25 13:53 UTC, iurynogueira commented on projects/ion/src/lib/alert/alert.component.html
> +  }"
check with [class.without-background]="hideBackground"

2022-10-25 16:59 UTC, lucasrasec approved these changes

2022-10-25 17:08 UTC, iurynogueira approved these changes

2022-10-25 17:10 UTC, iurynogueira commented on projects/ion/src/lib/alert/alert.component.scss
> +  border-color: transparent !important;
You can remove border

2022-10-25 18:03 UTC, VinicciusSantos commented on projects/ion/src/lib/alert/alert.component.scss
> +  border-color: transparent !important;
removed 👍

2022-10-26 17:13 UTC, iurynogueira approved these changes

2022-10-27 19:59 UTC, merged