fix: single dropdown closing when a option is clicked
iurynogueira/ion pull request #269
Opened 2022-11-03 21:07 UTC by larissacard

2022-11-04 12:29 UTC, iurynogueira requested changes
nice work @larissacard 😄

2022-11-04 12:29 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.spec.ts
> +      expect(screen.queryByTestId('Option 1')).toBeNull();
```suggestion
      expect(screen.queryByTestId(options[0].label)).toBeNull();
```

This way you not need change the label in 2 places.

2022-11-04 12:29 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.ts
> +      this.showDropdown = true;
Try it. This way you not need change 2 times the var

```suggestion    
    if (this.multiple) {
      this.updateBadgeValue(selectedItems);
      return;
    }
    
    this.showDropdown = false;
```

2022-11-04 12:51 UTC, iurynogueira approved these changes

2022-11-08 11:59 UTC, Deeved approved these changes

2022-11-08 12:23 UTC, merged