Input counter
iurynogueira/ion pull request #274
Opened 2022-11-08 13:10 UTC by edsonsnunes

2022-11-08 18:58 UTC, iurynogueira requested changes

2022-11-08 18:58 UTC, iurynogueira commented on projects/ion/src/lib/input-counter/input-counter.component.ts
> +      this.changedValue.emit({ newValue: this.count });
```suggestion
      emitNewValue();
```

Create a function and replace here.

2022-11-08 18:58 UTC, iurynogueira commented on projects/ion/src/lib/input-counter/input-counter.component.ts
> +    this.changedValue.emit({ newValue: this.count });
and here

2022-11-10 11:49 UTC, iurynogueira approved these changes

2022-11-11 14:15 UTC, Deeved approved these changes

2022-11-16 11:35 UTC, merged