Input button
iurynogueira/ion pull request #297
Opened 2022-11-21 13:32 UTC by edsonsnunes

2022-11-21 19:00 UTC, iurynogueira requested changes

2022-11-21 19:00 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.spec.ts
> +    expect(button).toBeTruthy();
toBeInTheDocument()

2022-11-21 19:00 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.spec.ts
> +  //Falta condição de quando o input vai ser valido ou invalido
create a test case when click in button to check this emit handleClick

2022-11-23 11:16 UTC, iurynogueira reviewed
Waiting placeholder input

2022-11-23 12:13 UTC, iurynogueira requested changes

2022-11-23 12:13 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.ts
> +  @Input() placeholderInput = 'Placeholder';
```suggestion
  @Input() placeholder = 'Placeholder';
```

2022-11-23 12:13 UTC, iurynogueira commented on projects/ion/src/lib/input/input.component.ts
> +  @Input() placeholderInput = 'Placeholder';
optional value

2022-11-25 16:58 UTC, luccskywalker commented on projects/ion/src/lib/input/input.component.html
> +    Button
Aqui não era para ser o valor de uma variável?

2022-12-02 17:37 UTC, luccskywalker approved these changes

2022-12-02 17:43 UTC, iurynogueira approved these changes

2022-12-02 17:46 UTC, iurynogueira commented
check cursor pointer

2022-12-02 18:00 UTC, merged