305 implement search field in dropdown
iurynogueira/ion pull request #324
Opened 2022-11-24 15:28 UTC by mizek1

2022-12-01 17:20 UTC, iurynogueira requested changes

2022-12-05 11:27 UTC, iurynogueira approved these changes

2022-12-05 15:50 UTC, AlyssonMascarenhas approved these changes
Good job, just review the conflicts

2022-12-05 17:56 UTC, iurynogueira commented on projects/ion/src/lib/dropdown/dropdown.component.spec.ts
> +    expect(screen.getByTestId('input-element')).toBeInTheDocument();
Add a const to this id.

2022-12-06 12:11 UTC, merged