312 - adding chip selector in card
iurynogueira/ion pull request #338
Opened 2022-12-01 11:53 UTC by VinicciusSantos

2022-12-01 17:45 UTC, iurynogueira requested changes

2022-12-01 17:45 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.spec.ts
> +  it('should render chips', async () => {
Check chips has displaying in screen by label, I suggest use of it.each(yourChipsArray) and expect element with chip label on screen.

2022-12-01 18:35 UTC, VinicciusSantos commented on projects/ion/src/lib/card/card.component.spec.ts
> -  imports: [CommonModule, ButtonModule],
to use the ButtonModule, I need to make a little change to it by adding the DropdownComponent in the exports:
![image](https://user-images.githubusercontent.com/90062413/205132423-6622badb-51d6-4ba4-b795-1290ce7010fe.png)

by doing this i would also remove the components declarations in .mdx file.
Can i do this?

2022-12-02 11:44 UTC, iurynogueira requested changes

2022-12-02 11:44 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.ts
> +    if (event['chipSelected'])
```suggestion
    if (event.chipSelected)
```

2022-12-02 11:44 UTC, iurynogueira commented on projects/ion/src/lib/card/card.component.ts
> +      this.indexOfChipSelected = event.chipSelected['index'];
```suggestion
      this.indexOfChipSelected = event.chipSelected.index;
```

2022-12-02 11:59 UTC, iurynogueira approved these changes

2022-12-02 17:07 UTC, merged