chip
iurynogueira/ion pull request #34
Opened 2022-07-18 13:32 UTC by edsonsnunes

fix #33

2022-07-18 16:55 UTC, iurynogueira commented
Faltou o disabled

2022-07-18 18:38 UTC, iurynogueira requested changes

2022-07-18 18:38 UTC, iurynogueira commented on projects/ion/src/lib/chip/chip.component.html
> +    'chip-disabled' : disabled}">
```suggestion
>
```

2022-07-18 18:38 UTC, iurynogueira commented on projects/ion/src/lib/chip/chip.component.html
> +    'chip-disabled' : disabled}">
Add [disabled]="disabled" in HTML tag and inner CSS add button[disabled] { style.... }

2022-07-21 12:28 UTC, iurynogueira approved these changes
nice work!

2022-07-21 21:47 UTC, Deeved approved these changes

2022-07-25 12:07 UTC, merged