Button Component
iurynogueira/ion pull request #36
Opened 2022-07-19 02:01 UTC by Deeved

Was adding to the Button Component:

**Types:**
- primary
- secundary
- ghost
- dashed

**Variation of types:**
- danger

**Sizes**
- sm 
- md
- lg
- xl

**"Behaviors" Styles**
- focus
- disabled
- hover

**Actions**
- click 

**Tests**
- types
- danger
- sizes

2022-07-19 12:10 UTC, iurynogueira requested changes
Good work! That is great!

2022-07-19 12:10 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.html
> +  [class]="'ion-btn-' + type + ' ion-btn-' + size"
@edsonsnunes Check this, you can use this solution to your problem of sizes.

2022-07-19 12:10 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.scss
> +}
add &:focus in button class.

2022-07-19 12:10 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.scss
> +}
same here

2022-07-19 12:10 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.spec.ts
> +  });
Nice! You can improve this separating this in a describe.

2022-07-19 12:10 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.ts
> +    this._danger = this.danger === 'true' ? true : false;
I believe that we can improve this using boolean types to avoid this "cast" 🤔

2022-07-19 12:18 UTC, iurynogueira commented
Don't forget doc in storybook.

2022-07-19 16:24 UTC, mizek1 commented
You can update your branch and use theme to customize your button. 😄

2022-07-21 12:32 UTC, iurynogueira requested changes

2022-07-21 12:32 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.scss
> +    box-shadow: 0px 0px 0px 2px $neutral-1, 0px 0px 0px 4px$primary-5;
```suggestion
    box-shadow: 0px 0px 0px 2px $neutral-1, 0px 0px 0px 4px $primary-5;
```

2022-07-21 12:32 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.scss
> +}
use &. Same strategy of button.

2022-07-21 12:32 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.spec.ts
> +  });
change to expect to toHaveClass
```suggestion
  it('should render a button with the ion-btn-primary class when type="primary" is passed', async () => {
    await render(ButtonComponent, {
      componentProperties: { type: 'primary' },
    });
    expect(screen.findByRole('button')).ToHaveClass('ion-btn-primary');
  });
```

2022-07-21 12:32 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.spec.ts
> +});
same here.

2022-07-25 12:18 UTC, iurynogueira requested changes

2022-07-25 12:18 UTC, iurynogueira commented on stories/Button.stories.mdx
> +- `loading`. Indica que o botão não está preparado para disparar a ação. Como por exemplo, esperando uma resposta do servidor ou preparando e/ou processando algum recurso interno. O evento de clique
```suggestion
- `loading`. Indica que o botão não está preparado para disparar a ação. Como por exemplo, esperando uma resposta do servidor ou preparando e/ou processando algum recurso interno. O evento de clique do botão é desativado quando o loading está ativo. É um boolean e opcional. Por padrão é `[loading] = false`.
```

2022-07-25 16:14 UTC, mizek1 requested changes

2022-07-26 13:00 UTC, iurynogueira requested changes

2022-07-26 13:00 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.ts
> +    if (!this.loading) {
Add a test case to this. "should not call event when is loading"

2022-07-26 14:33 UTC, iurynogueira approved these changes

2022-07-26 14:33 UTC, iurynogueira commented on projects/ion/src/lib/button/button.component.spec.ts
> +  it('should not call event when is loading', async () => {
Nice! 😄

2022-07-26 14:36 UTC, edsonsnunes approved these changes

2022-07-26 14:38 UTC, MarcosOliveir4 requested changes

2022-07-26 14:38 UTC, MarcosOliveir4 commented on projects/ion/src/lib/button/button.component.spec.ts
> +  customProps: IonButtonProps = { label: 'button' }
```suggestion
  customProps: IonButtonProps = { label: defaultName }
```

2022-07-26 14:53 UTC, merged