352 add select from items per page in table and smart table pagination
iurynogueira/ion pull request #360
Opened 2022-12-08 12:27 UTC by larissacard

2022-12-13 14:13 UTC, iurynogueira requested changes

2022-12-13 14:13 UTC, iurynogueira commented on projects/ion/src/lib/table/table.component.scss
> -  overflow-y: auto;
The table need max-height

2023-01-03 14:21 UTC, iurynogueira approved these changes

2023-01-04 11:37 UTC, mizek1 approved these changes

2023-01-05 12:01 UTC, merged