Tab
iurynogueira/ion pull request #42
Opened 2022-07-21 14:51 UTC by edsonsnunes

2022-07-21 16:39 UTC, iurynogueira requested changes
Nice work! Don't forget of add stories.

2022-07-21 16:39 UTC, iurynogueira commented on projects/ion/src/lib/tab/tab.component.ts
> +export type Size = 'sm' | 'md' | 'lg';
```suggestion
export type TabSize = 'sm' | 'md' | 'lg';
```

change this not to confuse with chip size.

2022-07-26 13:23 UTC, iurynogueira requested changes

2022-07-26 13:23 UTC, iurynogueira commented on README.md
> +> > > > > > > c497977328053cfb30bfc66a488ec7b3f1f1d35c
Fix conflict

2022-07-26 13:23 UTC, iurynogueira commented on projects/ion/src/lib/tab/tab.component.spec.ts
> +  it.each(['md', 'lg'])(
```suggestion
  it.each(['sm', 'md', 'lg'])(
```

2022-07-26 17:41 UTC, iurynogueira approved these changes

2022-07-26 17:56 UTC, iurynogueira approved these changes

2022-07-26 17:56 UTC, iurynogueira commented on projects/ion/src/lib/tab/tab.component.ts
> +  @Input('direction') direction?: Direction = 'bottom';
```suggestion
  @Input() tabSize?: TabSize = 'sm';
  @Input() disabled?: boolean;
  @Input() selected?: boolean;
  @Input() direction?: Direction = 'bottom';
```

2022-07-26 19:08 UTC, MarcosOliveir4 requested changes

2022-07-26 19:08 UTC, MarcosOliveir4 commented on projects/ion/src/lib/tab/tab.component.html
> +  {{ label }}
in this situation the label will not give any error if you do not pass the label through the attribute.
there are two ways to adjust this

1° in the html file
`{{ label || 'Configure uma label' }}`

2° in the ts file
`@Input() label = "Configure uma label"`

2022-07-26 20:18 UTC, Deeved approved these changes

2022-07-27 11:18 UTC, merged