feat:  storie #52
iurynogueira/ion pull request #53
Opened 2022-07-27 12:38 UTC by edsonsnunes

2022-07-29 11:54 UTC, iurynogueira requested changes

2022-07-29 11:54 UTC, iurynogueira commented on stories/Tab.stories.ts
> +  size: 'left',
```suggestion
  size: 'left',
```

border?

2022-07-29 12:11 UTC, mizek1 requested changes

2022-07-29 12:11 UTC, mizek1 commented on stories/Tab.stories.ts
> +import { TabComponent } from 'projects/ion/src/lib/tab/tab.component';
```suggestion
import { TabComponent } from '../projects/ion/src/lib/tab/tab.component';
```
This import is breaking the build when you run storybook.

2022-07-29 12:11 UTC, mizek1 commented on stories/Tab.stories.ts
> +  size: 'sm',
```suggestion
  tabSize: 'sm',
```
Your args should have the same name that your component's inputs.

2022-07-29 12:11 UTC, mizek1 commented on stories/Tab.stories.ts
> +  size: 'sm',
Same for the args below.

2022-07-29 12:11 UTC, mizek1 commented on stories/Tab.stories.ts
> +  size: 'bottom',
```suggestion
  direction: 'bottom',
```

2022-08-01 17:12 UTC, iurynogueira approved these changes

2022-08-01 18:28 UTC, Deeved approved these changes

2022-08-01 20:22 UTC, mizek1 approved these changes

2022-08-02 11:34 UTC, merged