feat: icon in tab #47
iurynogueira/ion pull request #61
Opened 2022-08-02 13:10 UTC by mizek1

fix #47

2022-08-02 14:07 UTC, iurynogueira requested changes

2022-08-02 14:07 UTC, iurynogueira commented on projects/ion/src/lib/tab/tab.component.scss
>      border-color: $primary-3;
@mixin make sense?

2022-08-02 14:32 UTC, Deeved commented on projects/ion/src/lib/tab/tab.component.scss
> +@mixin icon-color($color) {
I like it! :smile:

2022-08-02 14:33 UTC, Deeved approved these changes

2022-08-02 15:04 UTC, mizek1 commented on projects/ion/src/lib/tab/tab.component.scss
>      border-color: $primary-3;
Nice, I think mixin make sense here too!

2022-08-03 20:50 UTC, AlyssonMascarenhas commented
Good job!

2022-08-03 20:50 UTC, AlyssonMascarenhas approved these changes

2022-08-04 12:11 UTC, iurynogueira requested changes
🎉

2022-08-04 12:11 UTC, iurynogueira commented on projects/ion/src/lib/tab/tab.component.spec.ts
> +    const elementRendered = document.getElementById('ion-icon-trash');
You can improve this returning `document.getElementById('ion-icon-trash');` in sut.

2022-08-04 12:11 UTC, iurynogueira commented on projects/ion/src/lib/tab/tab.component.spec.ts
> +    await sut({ label: defaultName, iconType: 'trash' });
```suggestion
    const elementRendered = await sut({ label: defaultName, iconType: 'trash' });
```

2022-08-04 12:11 UTC, iurynogueira commented on projects/ion/src/lib/tab/tab.component.spec.ts
>  };
```suggestion
const sut = async (customProps?: IonTabProps) => {
  await render(TabComponent, {
    componentProperties: customProps || {
      label: defaultName,
    },
    imports: [CommonModule],
    declarations: [IonIconComponent],
  });
  
  return document.getElementById('ion-icon-trash')
};
```

2022-08-04 17:14 UTC, iurynogueira approved these changes

2022-08-04 17:15 UTC, merged