Ion grid
iurynogueira/ion pull request #87
Opened 2022-08-11 14:54 UTC by Deeved

[#49 ](https://github.com/iurynogueira/ion/issues/49)

Criando componentes `ion-row` e `ion-col`, junto com a documentação e 'testes'.
Os componentes não possuem nenhum input.

2022-08-16 12:44 UTC, iurynogueira requested changes
Check tests

2022-08-16 12:44 UTC, iurynogueira commented on projects/ion/src/lib/row/row.component.scss
> +      padding-left: 8px;
I believe that you can use spacing here.

2022-08-16 12:44 UTC, iurynogueira commented on stories/Grid.stories.mdx
> +<Meta title="Ion/Design Tokens/grid" />
```suggestion
<Meta title="Ion/Design Tokens/Grid" />
```

2022-08-17 11:59 UTC, iurynogueira approved these changes

2022-08-17 11:59 UTC, iurynogueira commented
AWESOME!
![festa](https://user-images.githubusercontent.com/6165180/185113078-a4c62e75-1f73-45f9-936c-e9f5154eae71.gif)
!

2022-08-19 11:24 UTC, lucasrasec approved these changes

2022-08-22 12:21 UTC, merged